name: pytest

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - uses: actions/checkout@v4
    - name: Run pytest
      run: uv run --all-extras pytest .
