name: pytest

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: tox-dev/action-pre-commit-uv@v1
    - name: Run pytest
      run: uv run pytest .
